---
################ INPUT ################
datasets:
 - input/part_one
 - input/part_two

################ RESOURCES ################
dbsnp_map: data/dbsnp151_pos.map
dbsnp_chr: data/dbsnp151_chr.map


################ SOFTWARE ################

plink: /home/joel/PLINK/plink
shapeit: /home/joel/Documents/GWAS/joined/bin/shapeit.v2.904.3.10.0-693.11.6.el7.x86_64/bin/shapeit
